### ISSUE TITLE
sketch fusion

### ISSUE THREAD

**Issue by FrancisVega** [turbobabr/sketch-ace-jump#1]
Hi! first sorry because this is not an real issue.
I would like using others libraries like lodash, ramda... in sketch plugin development like I see in your plugins :)
I've cloned your repos but I miss the plugin sketch fusion, Is it publicy available? Or if you have some clues of how I can setup a repo with node modules I would be very grateful :(

Again, that it not an issue, delete the msg if you think it convenient.

Thanks

**Comment by turbobabr** [comment]
Hi! Yeah, there's a missing webpack plugin. I'll publish it next week, meanwhile you could check out @mathieudutour 's `git-sketch` plugin that also uses custom bundling ES6 and npm modules:
https://github.com/mathieudutour/git-sketch-plugin
